export const MOCK_COLLEGES = [
  {
    _id: 'mock-rvce',
    name: 'R.V. College of Engineering',
    location: 'Bangalore',
    type: 'Private',
    image: '/images/hero-campus.png',
    ranking: 8,
    fees: { annual: 245000 },
    coursesOffered: [
      { name: 'B.Tech Computer Science', level: 'UG' },
      { name: 'M.Tech VLSI', level: 'PG' },
    ],
  },
  {
    _id: 'mock-bmsce',
    name: 'BMS College of Engineering',
    location: 'Bangalore',
    type: 'Private',
    image: '/images/hero-journey.png',
    ranking: 14,
    fees: { annual: 198000 },
    coursesOffered: [
      { name: 'B.Tech Information Science', level: 'UG' },
      { name: 'Information Technology', level: 'UG' },
    ],
  },
  {
    _id: 'mock-uvce',
    name: 'UVCE',
    location: 'Bangalore',
    type: 'Government',
    image: '/images/hero-student-win.png',
    ranking: 18,
    fees: { annual: 42000 },
    coursesOffered: [
      { name: 'B.E. Mechanical Engineering', level: 'UG' },
      { name: 'M.Tech Structural Engineering', level: 'PG' },
    ],
  },
  {
    _id: 'mock-pes',
    name: 'PES University',
    location: 'Bangalore',
    type: 'Deemed',
    image: '/images/hero-campus.png',
    ranking: 12,
    fees: { annual: 360000 },
    coursesOffered: [
      { name: 'B.Tech Electronics', level: 'UG' },
      { name: 'MCA', level: 'PG' },
    ],
  },
  {
    _id: 'mock-manipal',
    name: 'Manipal Institute of Technology',
    location: 'Manipal',
    type: 'Deemed',
    image: '/images/hero-journey.png',
    ranking: 9,
    fees: { annual: 410000 },
    coursesOffered: [
      { name: 'B.Tech Artificial Intelligence', level: 'UG' },
      { name: 'M.Sc Data Science', level: 'PG' },
    ],
  },
  {
    _id: 'mock-nitk',
    name: 'NITK Surathkal',
    location: 'Mangalore',
    type: 'Government',
    image: '/images/hero-student-win.png',
    ranking: 5,
    fees: { annual: 165000 },
    coursesOffered: [
      { name: 'B.Tech Civil Engineering', level: 'UG' },
      { name: 'M.Tech Computer Science', level: 'PG' },
    ],
  },
  {
    _id: 'mock-christ',
    name: 'Christ University',
    location: 'Bangalore',
    type: 'Deemed',
    image: '/images/hero-campus.png',
    ranking: 22,
    fees: { annual: 175000 },
    coursesOffered: [
      { name: 'BCA', level: 'UG' },
      { name: 'MCA', level: 'PG' },
      { name: 'BBA', level: 'UG' },
    ],
  },
  {
    _id: 'mock-jain',
    name: 'Jain University',
    location: 'Bangalore',
    type: 'Deemed',
    image: '/images/hero-journey.png',
    ranking: 41,
    fees: { annual: 155000 },
    coursesOffered: [
      { name: 'BCA', level: 'UG' },
      { name: 'MBA', level: 'PG' },
    ],
  },
  {
    _id: 'mock-iimk',
    name: 'Alliance School of Business',
    location: 'Bangalore',
    type: 'Private',
    image: '/images/hero-student-win.png',
    ranking: 35,
    fees: { annual: 280000 },
    coursesOffered: [
      { name: 'MBA', level: 'PG' },
      { name: 'BBA', level: 'UG' },
    ],
  },
  {
    _id: 'mock-reva',
    name: 'REVA University',
    location: 'Bangalore',
    type: 'Private',
    image: '/images/hero-campus.png',
    ranking: 48,
    fees: { annual: 125000 },
    coursesOffered: [
      { name: 'B.Sc Computer Science', level: 'UG' },
      { name: 'M.Sc Biotechnology', level: 'PG' },
    ],
  },
  {
    _id: 'mock-kletech',
    name: 'KLE Technological University',
    location: 'Hubli',
    type: 'Private',
    image: '/images/hero-journey.png',
    ranking: 27,
    fees: { annual: 138000 },
    coursesOffered: [
      { name: 'B.Tech Computer Science', level: 'UG' },
      { name: 'Diploma in Mechanical', level: 'Diploma' },
    ],
  },
  {
    _id: 'mock-sjce',
    name: 'JSS Science and Technology University',
    location: 'Mysore',
    type: 'Government-Aided',
    image: '/images/hero-student-win.png',
    ranking: 19,
    fees: { annual: 89000 },
    coursesOffered: [
      { name: 'B.E. Information Technology', level: 'UG' },
      { name: 'M.Tech Information Technology', level: 'PG' },
    ],
  },
  {
    _id: 'mock-poly',
    name: 'Government Polytechnic',
    location: 'Mysore',
    type: 'Government',
    image: '/images/hero-campus.png',
    ranking: 62,
    fees: { annual: 18000 },
    coursesOffered: [
      { name: 'Diploma in Computer Science', level: 'Diploma' },
      { name: 'Diploma in Civil', level: 'Diploma' },
    ],
  },
  {
    _id: 'mock-law',
    name: 'National Law School of India University',
    location: 'Bangalore',
    type: 'Government',
    image: '/images/hero-journey.png',
    ranking: 1,
    fees: { annual: 215000 },
    coursesOffered: [
      { name: 'B.A. LL.B', level: 'UG' },
    ],
  },
];
